impl shadow realm as js builtins
philomates/WebKit pull request #1
Opened 2021-09-09 16:25 UTC by philomates

2021-09-09 16:26 UTC, philomates commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +JSC_DEFINE_HOST_FUNCTION(importInRealm, (JSGlobalObject* globalObject, CallFrame* callFrame))
mostly copied and adapted from https://github.com/WebKit/WebKit/blob/fca70ae1e2cf0eeb3532d29a16e0f22a273ee3c5/Source/JavaScriptCore/runtime/JSGlobalObjectFunctions.cpp#L813-L835

2021-09-09 16:26 UTC, philomates commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +    RETURN_IF_EXCEPTION(scope, { });
note the difference from https://github.com/WebKit/WebKit/blob/main/Source/JavaScriptCore/runtime/JSGlobalObjectFunctions.cpp#L824
In the case here, according to the test262 suite, we want to throw outside the promise if `toString` has issues. I think the difference here achieves that (at least I had to make the change to get things passing)

2021-09-09 16:26 UTC, philomates commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +        return throwVMTypeError(globalObject, scope, "'this' should be a ShadowRealm");
when should one use `throwVMTypeError` instead of `throwTypeError`?

2021-09-09 16:26 UTC, philomates commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +    auto* internalPromise = realmGlobalObject->moduleLoader()->importModule(realmGlobalObject, specifier, jsUndefined(), sourceOrigin);
this creates an internal promise somehow associated with the realm global object, but we later do `resolve` on the original global object. I can't see anything clearly problematic with this, but felt worth bringing attention to this

2021-09-09 16:27 UTC, philomates commented on Source/JavaScriptCore/runtime/JSGlobalObject.cpp
> +}
this was the best way I could think of creating a new global object with a custom method table. We grab the method table from the original global object in https://github.com/WebKit/WebKit/pull/8/files#diff-44ebd0942590c3af4f75c8833b1b8f2dd9d649fd9e7dcc7a9e1410df5711c22fR33, which might be defined in `jsc.cpp` or elsewhere in webkit when run in the browser context.

2021-09-09 16:27 UTC, philomates commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +      return @wrap(m[bindingStr]);
is there a better way to do this prop check/lookup?

2021-09-09 16:27 UTC, philomates commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +
my (idiomatic) JS is horrible so in general be thorough with this file

2021-09-09 20:19 UTC, caiolima requested changes
The patch is going in a good direction. I left some comments on things we need to change. I also think we need to add a feature flag for ShadowRealms and start writing stress tests, since Test262 is not run on Webkit’s CI for patches, only when they are landed.

2021-09-09 20:19 UTC, caiolima commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +    auto* internalPromise = realmGlobalObject->moduleLoader()->importModule(realmGlobalObject, specifier, jsUndefined(), sourceOrigin);
Those different global objects are really confusing my mind from time to time. I hope we have tests covering things there.

2021-09-09 20:19 UTC, caiolima commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +        return throwVMTypeError(globalObject, scope, "First arg should be a ShadowRealm");
s/arg/argument/

2021-09-09 20:19 UTC, caiolima commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +        return throwVMTypeError(globalObject, scope, "First arg should be a ShadowRealm");
Since it’s internal, I was wondering if this could be an assert.

2021-09-09 20:19 UTC, caiolima commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +        return throwVMTypeError(globalObject, scope, "Second argument must be a string");
ditto

2021-09-09 20:19 UTC, caiolima commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +  let result = @evalInRealm(this, evalStr)
We need to validate here if both `this` and `evalStr` are valid inputs. otherwise, the errors from  `evalInRealm` won’t make much sense to  users and it’ll be exposing some internals that are not good to be exposed.

2021-09-09 20:19 UTC, caiolima commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +{
We also need to validate inputs here on JS level. This function can be called with anything, including `this` being overridden

2021-09-09 20:19 UTC, caiolima commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +        throwTypeError(globalObject, scope, "Error encountered during evaluation"_s);
I’m wondering if this exception will override the exception thrown by eval’ed code...

2021-09-10 09:31 UTC, philomates commented on Source/JavaScriptCore/runtime/ShadowRealmConstructor.cpp
> +const ClassInfo ShadowRealmConstructor::s_info = { "Function", &InternalFunction::s_info, nullptr, nullptr, CREATE_METHOD_TABLE(ShadowRealmConstructor) };
I wondered about that too but saw that other constructors use `Function`

2021-09-10 09:33 UTC, philomates commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +function evaluate(evalStr)
I didn't see a way to name this differently without changing the API of ShadowRealm itself

2021-09-10 09:41 UTC, philomates commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +        return throwVMTypeError(globalObject, scope, "First arg should be a ShadowRealm");
can you explain this a bit more; I see other `JSC_DEFINE_HOST_FUNCTION` that are throwing type errors instead of asserting

2021-09-10 09:50 UTC, philomates commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +        throwTypeError(globalObject, scope, "Error encountered during evaluation"_s);
Like this?
```
> (new ShadowRealm()).evaluate("throw Error(\"hidden secret\")")
Exception: TypeError: Error encountered during evaluation
```

2021-09-10 10:04 UTC, philomates commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +        return throwVMTypeError(globalObject, scope, "First arg should be a ShadowRealm");
Is it that we can do an assert here because we should check this at the JS level?

2021-09-10 13:17 UTC, philomates commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +      const wrappedArgs = args.map(@wrap);
Hmm, I couldn't figure out how to use `@Map`. Any tips?

2021-09-10 13:18 UTC, philomates commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +function wrap(target)
So I tried to change this and the build kept breaking :/
I'm also having lots of issues updating this file, compiling, and getting results that indicate the changes weren't compiled; maybe that is related

2021-09-10 13:21 UTC, philomates commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +    delete wrapped['length'];
I was going off of this:
```
> var x = () => { 1 }
undefined
> Object.getOwnPropertyNames(x)
length,name
```

2021-09-10 13:43 UTC, philomates commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +    if (bindingStr in m) {
do modules have a prototype chain? 

Like if I run 
```
 var r = new ShadowRealm();
 r.evaluate("Object.prototype.whatever = 1");
 await r.importValue("./fruit.js", "whatever");
```
where `fruit.js` doesn't have `whatever` defined/exported, it fails with
```
Exception: TypeError: %ShadowRealm%.importValue requires |exportName| to exist in the |specifier|
```

2021-09-10 13:53 UTC, philomates commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +      @throwTypeError("`%ShadowRealm%.evaluate requires that the |sourceText| argument be a string");
is this robust enough or should we also do `|| sourceText instanceof String` to get the case where a `new String(123)` arg is passed in?

2021-09-10 13:53 UTC, philomates commented on Source/JavaScriptCore/runtime/JSGlobalObject.cpp
> +    }
should I put more in this feature flag conditional?

2021-09-10 13:58 UTC, philomates commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +    }
since `importInRealm` is called by a builtin, we can probably remove this check, right?

2021-09-10 16:20 UTC, caiolima commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +        return throwVMTypeError(globalObject, scope, "'this' should be a ShadowRealm");
It’s really a question I don’t have the answer...I didn’t even know we had both.

2021-09-10 16:22 UTC, caiolima commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +      return @wrap(m[bindingStr]);
Not in this computed case. But such access will be optimized out on DFG and FTL if possible.

2021-09-10 16:23 UTC, caiolima commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +function wrap(target)
Hum...I remember having troubles like that before. I used to force a clean build IIRC.

2021-09-10 16:23 UTC, caiolima commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +      const wrappedArgs = args.map(@wrap);
I’m sorry, I meant `@map`. If this is not around, we will probably need to include `mapPrivateName` on Array prototypes to make it available here.

2021-09-10 16:25 UTC, caiolima commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +    if (bindingStr in m) {
I don’t think they have. I remember people saying em that modules are different than common objects. If this is the case, I think we might be fine.

2021-09-10 16:26 UTC, caiolima commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +    delete wrapped['length'];
Oh right, `Object.getOwnPropertyNames` is only going to show enumerable properties IIRC. We probably need to take a look at spec to be sure there.

2021-09-10 16:26 UTC, caiolima commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +function evaluate(evalStr)
Oh, I think this is fine to keep it evaluate. My bad, because I thought it was a global operation.

2021-09-10 16:28 UTC, caiolima commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +        return throwVMTypeError(globalObject, scope, "First arg should be a ShadowRealm");
That’s what I was thinking about. How those errors show up for users when they call `ShadowRealm.prototype.evaluate(1, Symbol(“foo”));`, fox example?

2021-09-10 16:29 UTC, caiolima commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +        throwTypeError(globalObject, scope, "Error encountered during evaluation"_s);
Yes, just like that. I think you shared this internally, and spec says we should override it, right?

2021-09-10 16:31 UTC, caiolima commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +      @throwTypeError("`%ShadowRealm%.evaluate requires that the |sourceText| argument be a string");
Spec says `If Type(sourceText) is not String, throw a TypeError exception.`, so I think for String Objects (like `new String(123)`) we should throw, because they are considered Objects. Might be worth it validate this with spec experts!

2021-09-10 16:33 UTC, caiolima commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +    }
I think so. Placing an assert might make bugs there more obvious, BTW

2021-09-10 16:47 UTC, philomates commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +      const wrappedArgs = args.map(@wrap);
`@map` doesn't exist and I couldn't figure out how `mapPrivate..` might apply.
what about this: https://github.com/philomates/WebKit/pull/1/commits/79b31eda9fec2b54db6857fc293485d3c9f6dea3 ?

2021-09-10 16:49 UTC, philomates commented on Source/JavaScriptCore/runtime/ShadowRealmPrototype.cpp
> +        return throwVMTypeError(globalObject, scope, "First arg should be a ShadowRealm");
I switched it to an ASSERT and did the check on the JS side and it looks like this now, which seems correctl:
```
ShadowRealm.prototype.evaluate(1, Symbol("foo"));
Exception: TypeError: `%ShadowRealm%.evaluate requires that |this| be a ShadowRealm instance
```

2021-09-13 12:45 UTC, philomates commented on Source/JavaScriptCore/builtins/ShadowRealmPrototype.js
> +    delete wrapped['length'];
I looked at `FunctionPrototype` and `JSFunction` and didn't see anything else defined, aside from `name` and `length`

2021-09-21 14:01 UTC, caiolima reviewed
Patch LGTM. I think it’s ready to be shared on Bugzilla and ask for some review already.

2021-09-21 14:18 UTC, philomates commented on JSTests/stress/shadow-realm-evaluate.js
> +}
I'll ask Leo about it

2021-09-21 18:42 UTC, leobalter commented on JSTests/stress/shadow-realm-evaluate.js
> +}
We have a [very shy assertion](https://github.com/tc39/test262/blob/main/test/built-ins/ShadowRealm/prototype/evaluate/errors-from-the-other-realm-is-wrapped-into-a-typeerror.js#L18) picking the SyntaxError. 

The assert.throws in Test262 verifies the identity of the expected error constructor being Realm related.

I believe this is a good opportunity to add an [assertion for assert.throws](https://github.com/tc39/test262/tree/main/test/harness) making sure the `err.constructor === expectedErrCtor` in order to avoid identity discontinuity issues.

2021-09-21 20:39 UTC, leobalter commented on JSTests/stress/shadow-realm-evaluate.js
> +}
For the records, we now make sure that assert.throws won't give false positive for cross realms error constructors. https://github.com/tc39/test262/pull/3208

2021-09-21 20:41 UTC, leobalter commented on JSTests/stress/shadow-realm-evaluate.js
> +}
which means that in Test262 [tests like this](https://github.com/tc39/test262/blob/main/test/built-ins/ShadowRealm/prototype/evaluate/errors-from-the-other-realm-is-wrapped-into-a-typeerror.js#L18-L21) are good enough for their purposes of verifying the proper identity.

2021-09-22 10:11 UTC, philomates commented on JSTests/stress/shadow-realm-evaluate.js
> +}
Nice!
Come to think of it, I was getting test262 failures last week essentially saying "expected a `SyntaxError` but got a `SyntaxError`". At the time I was super confused but now I'm realizing that it was the bug in my implementation where errors created in the child realm using one global object were being passed back unwrapped and being compared to errors in the parent realm, which has a different global object. Being new to JS I didn't realize that this test failure could imply this issues but I'm now seeing the connection after writing the explicit `$.globalObjectFor(err)` checks. 
Long story short, test262 seemed to be correctly failing when errors escaped their realms unmodified.

2021-09-22 15:19 UTC, philomates commented
moved to https://bugs.webkit.org/show_bug.cgi?id=230602

2021-09-22 15:19 UTC, closed without merging